name: domain
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.2.0 <4.0.0'

dependency_overrides:
  flutter:
    sdk: flutter
  analyzer: ^6.4.1

dependencies:
  async: 2.11.0
  dartx: ^1.2.0
  flutter:
    sdk: flutter
  get_it: ^7.6.8
  injectable: ^2.4.1
  meta: ^1.11.0
  resources:
    path: ../resources
  rxdart: 0.27.7
  shared:
    path: ../shared
  tuple: 2.0.2

dev_dependencies:
  build_runner: ^2.4.9
  custom_lint: ^0.6.4
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
  freezed: ^2.5.0
  freezed_annotation: ^2.4.1
  injectable_generator: ^2.6.1
  logging: ^1.2.0
  mocktail: ^1.0.3
  nals_lints:
    path: ../nals_lints
